---
# https://book.keybase.io/docs/server/our-code-signing-key
- name: Install keybase apt keys
  tags: keybase
  become: true
  ansible.builtin.apt_key:
    url: https://keybase.io/docs/server_security/code_signing_key.asc
    id: 222B85B0F90BE2D24CFEB93F47484E50656D16C7
    state: present
    keyring: /usr/share/keyrings/keybase-archive-keyring.gpg

- name: Install keybase repo
  tags: keybase
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ [ansible_architecture] | map('extract', keybase_deb_architecture) | first }} signed-by=/usr/share/keyrings/keybase-archive-keyring.gpg]
      http://prerelease.keybase.io/deb stable main
    state: present
    filename: keybase

- name: Install keybase
  tags: keybase
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: keybase
    state: present
