---
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
platforms:
  - name: localhost
    connection: local
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
