---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify keybase is installed
      ansible.builtin.command: keybase --help
      register: keybase_help_result
      changed_when: false

    - name: Show keybase help output
      ansible.builtin.debug:
        var: keybase_help_result.stdout
