name: ansible-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        # optional (see below):
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""

  molecule:
    name: Molecule Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule ansible-core ansible-lint
      - name: Create symlink for role
        run: |
          cd molecule/default
          mkdir -p roles
          ln -sf ../../../roles/keybase roles/keybase
      - name: Run Molecule syntax check
        run: molecule syntax
      - name: Run Molecule verify
        run: molecule verify
